---
abstract: "Maintain session IDs using mobile phone's unique id"
author:
  - 'Tokuhiro Matsuno <tokuhirom AAJKLFJEF GMAIL COM>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  HTTP::Response: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-Session-State-MobileAgentID
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  HTTP::MobileAgent: 0.28
  HTTP::Session: 0.38
  Net::CIDR::MobileJP: 0.20
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.46
